// Shared StyleSheet for the /photo-picker flow, consumed by CameraPane +
// LibraryStrip. The picker chrome is deliberately dark-on-black (camera UI),
// so these are hardcoded rather than theme-derived; the two theme-dependent
// touches (accent Done bar, strip spinner) are applied inline by the panes.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cameraWrap: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  topBar: {
    position: 'absolute',
    top: 56,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  libraryShortcut: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  libraryShortcutText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  zoomPill: {
    position: 'absolute',
    top: 110,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  zoomPillText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.5,
  },
  shutter: {
    marginBottom: 32,
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderWidth: 4,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
  },
  doneBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'stretch',
    marginHorizontal: 16,
    marginBottom: 20,
    paddingVertical: 14,
    borderRadius: 14,
  },
  doneBarText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  permPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    padding: 24,
  },
  permText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  permButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  permButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  libraryStrip: {
    height: 110,
    backgroundColor: '#0a0a0a',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  libraryEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
  },
  libraryEmptyText: { color: '#bbb', fontSize: 13, textAlign: 'center' },
  thumb: {
    width: 86,
    height: 86,
    borderRadius: 8,
    backgroundColor: '#222',
    overflow: 'hidden',
  },
  thumbSelectedOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#fff',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  thumbCheck: {
    position: 'absolute',
    top: 5,
    right: 5,
    minWidth: 22,
    height: 22,
    paddingHorizontal: 5,
    borderRadius: 11,
    backgroundColor: '#147A4F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbCheckText: { color: '#fff', fontSize: 12, fontWeight: '800' },
});
