import { StyleSheet } from 'react-native';
import type { Theme } from '../../lib/theme';

export function gets(theme: Theme) {
  return StyleSheet.create({
    header: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 12,
      backgroundColor: theme.colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.hairline,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    eyebrow: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      color: theme.colors.accent,
    },
    title: { fontSize: 18, fontWeight: '800', color: theme.colors.ink, marginTop: 2 },
    closeBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.subtleSurface,
    },
    helpHint: { marginTop: 8, fontSize: 12, color: theme.colors.inkSoft },
    // Chip row
    chipRowWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.colors.background,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.hairline,
      gap: 8,
    },
    itemLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: '500',
      color: theme.colors.ink,
    },
    chip: {
      width: 40,
      height: 44,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: theme.colors.hairline,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.card,
    },
    // Accordion
    accordion: {
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.hairline,
      borderTopWidth: 0,
      padding: 12,
      gap: 10,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
      marginTop: -1,
    },
    accordionLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.danger,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    commentInput: {
      backgroundColor: theme.colors.subtleSurface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.dangerBorder,
      padding: 10,
      minHeight: 72,
      textAlignVertical: 'top',
      fontSize: 15,
      color: theme.colors.ink,
    },
    addPhotoSmall: {
      height: 72,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      borderStyle: 'dashed',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.background,
      flexDirection: 'row',
      gap: 8,
    },
    addPhotoText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.inkSoft,
    },
    thumbWrap: {
      width: 72,
      height: 72,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: theme.colors.subtleSurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    thumbDelete: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 8,
      backgroundColor: theme.colors.background,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.hairline,
    },
    bigCta: {
      minHeight: 64,
      backgroundColor: theme.colors.accent,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bigCtaText: { fontSize: 18, fontWeight: '800', color: theme.colors.white },
  });
}