import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

// web-app shares ONE component library with the Expo app: the universal
// primitives (rendered via react-native-web) plus the design tokens / theme /
// haptics / accessibility / animations they depend on. Those @root paths are
// allowed; every OTHER reach into the mobile codebase is still banned (share
// via Supabase, or port into web-app/src). This negative-lookahead regex
// matches the BANNED imports — any @root/* that isn't part of the shared lib.
const RESTRICTED_ROOT_REGEX =
  '^@root/(?!(components/(primitives|animations)|lib/(theme|ThemeContext|design-tokens|haptics|accessibility))($|/))';
const RESTRICTED_ROOT_MESSAGE =
  'web-app may import the SHARED component library (@root/components/primitives + the design tokens/theme/haptics/accessibility/animations it needs), but not other mobile code. Share everything else via Supabase, or port it into web-app/src.';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'node_modules',
      'coverage',
      'test-results',
      'playwright-report',
      'e2e-smoke', // Playwright specs run via `npm run smoke`, not ESLint
      'src/types/database.ts', // generated by `npm run gen:types`
      '*.config.js',
      '*.config.ts',
    ],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.es2022 },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // tsc (noUnusedLocals) is the source of truth for unused symbols; keep
      // ESLint's as a warning that respects the _-prefix escape hatch.
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // web-app shares the universal component library with the Expo app; any
      // OTHER reach into the repo root is still banned (see CLAUDE.md).
      'no-restricted-imports': [
        'warn',
        {
          patterns: [{ regex: RESTRICTED_ROOT_REGEX, message: RESTRICTED_ROOT_MESSAGE }],
        },
      ],
    },
  },
  {
    // Data layer is the one place allowed to import the Supabase client.
    files: ['src/pages/**', 'src/features/**', 'src/components/**'],
    rules: {
      'no-restricted-imports': [
        'warn',
        {
          patterns: [
            { regex: RESTRICTED_ROOT_REGEX, message: RESTRICTED_ROOT_MESSAGE },
            {
              group: ['@/lib/supabase'],
              message:
                'Do not call Supabase directly from UI. Use the data layer (lib/data, lib/db) instead.',
            },
          ],
        },
      ],
    },
  },
);
