// scripts/build-tokens.mjs — generate web token artifacts from the canonical
// lib/design-tokens.ts. Run with:  npm run tokens
//
// Outputs (all under web-app/src/generated/, regenerate — never hand-edit):
//   • tokens.css         — :root + .dark CSS custom properties
//   • tailwind-tokens.ts — colors/fontSize/borderRadius/boxShadow/spacing for
//                          tailwind.config.ts to spread into theme.extend
//
// This is the single mechanism that keeps web tokens in lockstep with mobile.
// Requires Node ≥ 22.6 (uses --experimental-strip-types to import the .ts source);
// the npm script passes that flag.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
// TOKENS_OUT_DIR override lets check-tokens-fresh.mjs regenerate into a temp dir.
const outDir = process.env.TOKENS_OUT_DIR
  ? resolve(process.env.TOKENS_OUT_DIR)
  : resolve(repoRoot, 'web-app/src/generated');

const tokens = await import(resolve(repoRoot, 'lib/design-tokens.ts'));
const {
  primary,
  neutral,
  semantic,
  highlight,
  typeScale,
  radii,
  shadowSpec,
  spaceUnit,
  semanticLight,
  semanticDark,
} = tokens;

const BANNER = `/* AUTO-GENERATED by scripts/build-tokens.mjs from lib/design-tokens.ts.
 * Do NOT edit by hand — run \`npm run tokens\` to regenerate. */`;

/** Convert #rgb/#rrggbb to "r, g, b" (for rgba()), or pass through rgba/transparent. */
function rgbTriplet(color) {
  if (color === 'transparent') return null;
  let hex = color.replace('#', '');
  if (hex.length === 3) hex = hex.split('').map((c) => c + c).join('');
  const r = parseInt(hex.slice(0, 2), 16);
  const g = parseInt(hex.slice(2, 4), 16);
  const b = parseInt(hex.slice(4, 6), 16);
  return `${r}, ${g}, ${b}`;
}

/** A ShadowSpec → CSS box-shadow string. */
function cssShadow(s) {
  const triplet = rgbTriplet(s.color);
  if (!triplet || s.opacity === 0) return 'none';
  return `${s.x}px ${s.y}px ${s.blur}px rgba(${triplet}, ${s.opacity})`;
}

// Spacing scale: multiples of the base unit (web-app uses up to ~20 → 80px).
const spacingSteps = [0, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 20];

// ── tokens.css ───────────────────────────────────────────────────────────────

const cssLines = [BANNER, ':root {'];
// Brand + neutral scales
for (const [k, v] of Object.entries(primary)) cssLines.push(`  --brand-${k}: ${v};`);
for (const [k, v] of Object.entries(neutral)) cssLines.push(`  --neutral-${k}: ${v};`);
// Semantic palette (success / warning / danger / info + soft variants)
for (const [k, v] of Object.entries(semantic)) cssLines.push(`  --${kebab(k)}: ${v};`);
// Spacing + radii
for (const n of spacingSteps) cssLines.push(`  --space-${String(n).replace('.', '_')}: ${n * spaceUnit}px;`);
for (const [k, v] of Object.entries(radii)) cssLines.push(`  --radius-${k}: ${typeof v === 'number' ? v + 'px' : v};`);
// Type ramp
for (const [k, v] of Object.entries(typeScale)) cssLines.push(`  --text-${k}: ${v.size}px;`);
// Shadows
for (const [k, v] of Object.entries(shadowSpec)) cssLines.push(`  --shadow-${k}: ${cssShadow(v)};`);
// Light semantic surfaces
for (const [k, v] of Object.entries(semanticLight)) cssLines.push(`  --${kebab(k)}: ${v};`);
cssLines.push('}');
// Dark semantic surfaces
cssLines.push('', '.dark {');
for (const [k, v] of Object.entries(semanticDark)) cssLines.push(`  --${kebab(k)}: ${v};`);
cssLines.push('}', '');

function kebab(s) {
  return s.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
}

// ── tailwind-tokens.ts ────────────────────────────────────────────────────────

const colors = {
  brand: primary,
  neutral,
  highlight,
  success: semantic.success,
  warning: semantic.warning,
  danger: semantic.danger,
  info: semantic.info,
};
const fontSize = Object.fromEntries(
  Object.entries(typeScale).map(([k, v]) => [k, [`${v.size}px`, { lineHeight: `${v.lineHeight}px`, letterSpacing: `${v.letterSpacing}em` }]])
);
const borderRadius = Object.fromEntries(
  Object.entries(radii).map(([k, v]) => [k, typeof v === 'number' ? `${v}px` : v])
);
const boxShadow = Object.fromEntries(Object.entries(shadowSpec).map(([k, v]) => [k, cssShadow(v)]));
const spacing = Object.fromEntries(spacingSteps.map((n) => [String(n), `${n * spaceUnit}px`]));

const tsOut = `${BANNER}
// Spread into tailwind.config.ts → theme.extend.
export const colors = ${JSON.stringify(colors, null, 2)} as const;
export const fontSize = ${JSON.stringify(fontSize, null, 2)} as const;
export const borderRadius = ${JSON.stringify(borderRadius, null, 2)} as const;
export const boxShadow = ${JSON.stringify(boxShadow, null, 2)} as const;
export const spacing = ${JSON.stringify(spacing, null, 2)} as const;
`;

// ── write ──────────────────────────────────────────────────────────────────

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'tokens.css'), cssLines.join('\n'));
writeFileSync(resolve(outDir, 'tailwind-tokens.ts'), tsOut);

console.log(`✓ tokens written to web-app/src/generated/ (brand-500 = ${primary[500]})`);
