// styles.ts - shared StyleSheets for the inspection wizard.

import { StyleSheet } from 'react-native';

export function getstyles(theme: any) {
  return StyleSheet.create({
  kbAccessory: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: theme.colors.card,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.hairline,
  },
  kbDoneBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  kbDoneText: {
    color: theme.colors.accent,
    fontSize: 16,
    fontWeight: '600',
  },
  accessoryBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  accessoryBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  accessoryBtnText: {
    fontSize: 15,
    fontWeight: '600',
  },
  topBar: {
    height: 48,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.card,
  },
  stepperText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.inkSoft,
  },
  closeBtn: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    paddingHorizontal: 4,
    justifyContent: 'center',
  },
  questionTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: theme.colors.ink,
    lineHeight: 34,
    textAlign: 'center',
    paddingHorizontal: 8,
    paddingVertical: theme.spacing(4),
  },
  chipRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingTop: 4,
  },
  assistChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.hairline,
    backgroundColor: theme.colors.card,
  },
  assistChipText: {
    fontSize: 16,
    color: theme.colors.inkSoft,
    fontWeight: '500',
  },
  choice: {
    flex: 1,
    paddingVertical: 18,
    alignItems: 'center',
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'transparent',
    gap: 6,
  },
  choiceText: { fontSize: 18, fontWeight: '700' },
  label: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.inkSoft,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  footer: {
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: theme.colors.card,
  },
  confirmOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.overlay,
  },
  confirmCard: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 340,
    gap: 4,
    ...theme.shadow.card,
  },
  statusOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 14,
  },
  harnessRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 10,
  },
  chip: {
    width: 40,
    height: 34,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: theme.colors.hairline,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.card,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  safetyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 14,
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  photoThumb: {
    width: 80,
    height: 80,
    backgroundColor: theme.colors.subtleSurface,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  photoTile: {
    width: 120,
    height: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.hairline,
    overflow: 'hidden',
  },
  addPhotoTile: {
    width: 120,
    height: 120,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.colors.hairline,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.subtleSurface,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  previewImage: {
    width: '90%',
    height: '70%',
  },
  previewDeleteBtn: {
    position: 'absolute',
    bottom: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: theme.colors.danger,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
  },
  previewCloseBtn: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
}

export const staticStyles = StyleSheet.create({
  statusOptionText: { flex: 1, fontSize: 15, fontWeight: '600' },
  harnessColLabel: { flex: 1, fontSize: 13 },
  harnessChipRow: { flexDirection: 'row', gap: 6 },
  gap8: { gap: 8 },
  gap10: { gap: 10 },
  gap14: { gap: 14 },
  gap16: { gap: 16 },
  gap18: { gap: 18 },
  padTop16: { paddingTop: 16 },
  padTop20: { paddingTop: 20 },
  padV8: { paddingVertical: 8 },
  padH16: { paddingHorizontal: 24 },
  padB12: { paddingBottom: 12 },
  padB16: { paddingBottom: 16 },
  padB24: { paddingBottom: 24 },
  flexRow: { flexDirection: 'row' },
  flexRowCenter: { flexDirection: 'row', alignItems: 'center' },
  center: { alignItems: 'center' },
  centerGap14: { alignItems: 'center', gap: 14 },
  centerPadV8Gap12: { alignItems: 'center', paddingVertical: 8, gap: 12 },
  rowCenterGap10: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  rowBetweenPadH4: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 4 },
  rowCenterGap12: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  mt24gap16: { marginTop: 24, gap: 16 },
  mt12: { marginTop: 12 },
  padH16gap8: { paddingHorizontal: 24, gap: 8 },
  stepScrollContent: { padding: 20, paddingBottom: 12, gap: 16 },
});

export const uploadPillStyles = StyleSheet.create({
  wrap: {
    position: 'absolute',
    top: 56,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(17,24,39,0.92)',
  },
  text: { color: '#FFFFFF', fontSize: 13, fontWeight: '600' },
});
